

import DashboardLayout from '@/components/dashboard-layout/DashBoardLayout'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dashboard Layout',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <DashboardLayout>{children}</DashboardLayout>
}
